### ISSUE TITLE
Add Redux 

### ISSUE THREAD

**Issue by margiechubin** [uiucwebmonkeys/scheedule#7]

**Comment by margiechubin** [comment]
I added redux to the project's package.json. Was there anything you wanted me to do to set it up in our app?

**Comment by pranaygp** [comment]
I was hoping you could check out the videos on egghead on redux (and/or use this http://redux.js.org/)

and then set up https://github.com/reactjs/react-redux with our codebase. that would essentially be adding it to package.json, and modifying the app.js file

**Comment by margiechubin** [comment]
Done! (Don't forget to run npm install whenever something is added to package.json)
For now, you can see the additions to the store logged in the console. I'm also only adding the text field for now and we can change the data representation later. The egghead tutorial and redux documentation are very useful!
